### ISSUE TITLE
Race condition

### ISSUE THREAD

**Issue by GitZamfir** [metricly/aws-ssm#1]
When installing via SSM on Windows. The msi installer is launched asynchronously and does not install the service before the Start-Server command is isssued.  This can be easily resolved by adding -Wait to the Start-Process powershell command.

**Comment by GitZamfir** [comment]
line 53:
          "Start-Process -Wait -FilePath 'msiexec.exe' -ArgumentList '/quiet /package https://repos.app.netuitive.com/windows-agent/75/X64/Release/CollectdWin-x64.msi NETUITIVE_API_KEY={{ WINDOWSAPIKEY }}'",

**Comment by codytipton** [comment]
Thanks for the find @GitZamfir  I'll make sure this gets addressed shortly.
